

-- insert dog 
  INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('1', '1000000001', 'Max', '2', '2017-07', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('2', '1000000002', 'Lulu', '1', '2020-08', 'tricolor', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('3', '1000000003', 'Denis', 'boxer', '2', '2018-01', 'brown', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('4', '1000000004', 'Honey', '1', '2020-03', 'white', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('5', '1000000005', 'Luna', 'pitbull', '1', '2020-04', 'brown', 'medium', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('6', '1000000006', 'Angi', '1', '2018-05', 'brown', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('7', '1000000007', 'Bruno', 'cane corso', '2', '2019-11', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('8', '1000000008', 'Nero', '2', '2021-04', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('9', '1000000009', 'Dia', '1', '2021-03', 'beige', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('10', '1000000010', 'Boby', '2', '2021-05', 'white', 'medium', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('11', '1000000011', 'Dodo', '2', '2020-12', 'brown', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('12', '1000000012', 'Rex', 'german shepherd', '2', '2021-09', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('13', '1000000013', 'July', '1', '2017-01', 'tricolor', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('14', '1000000014', 'Hope', '1', '2018-07', 'black and white', 'small', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('15', '1000000015', 'Drex', '2', '2020-07', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('16', '1000000016', 'Basti', 'dachshund', '2', '2022-05', 'black', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('17', '1000000017', 'Abby', '1', '2021-09', 'brown', 'medium', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('18', '1000000018', 'Carlos', '2', '2022-12', 'black and white', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('19', '1000000019', 'Indigo', '2', '2020-04', 'blue', 'large', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('20', '1000000020', 'Foxy', '2', '2018-11', 'white', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('21', '1000000021', 'Juno', '2', '2021-06', 'beige', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('22', '1000000022', 'Cleo', 'westie', '1', '2021-07', 'white', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('23', '1000000023', 'Flow', '2', '2022-02', 'white', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('24', '1000000024', 'Yoko', '1', '2018-07', 'brown', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('25', '1000000025', 'Zara', '1', '2017-03', 'blue', 'medium', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('26', '1000000026', 'Mavis', '2', '2021-06', 'black', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('27', '1000000027', 'Kate', '1', '2022-11', 'brown', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('28', '1000000028', 'Ellie', '1', '2021-04', 'black and white', 'small', '3');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('29', '1000000029', 'Dark', '2', '2017-12', 'brown', 'large', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('30', '1000000030', 'Coco', '1', '2019-12', 'black and white', 'small', '1');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('31', '1000000031', 'Mr', 'staffordshire', '2', '2018-04', 'brown', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('32', '1000000032', 'Kelly', 'labrador', '1', '2020-03', 'beige', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `size`, `status`) VALUES ('33', '1000000033', 'Ubul', '2', '2018-01', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `size`, `status`) VALUES ('34', '1000000034', 'Berg', '2', '2019-06', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `size`, `status`) VALUES ('35', '1000000035', 'Rob', '2', '2020-04', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('36', '1000000036', 'Don', 'bullterrier', '2', '2021-10', 'white', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `size`, `status`) VALUES ('37', '1000000037', 'Linda', '1', '2021-10', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('38', '1000000038', 'One', '1', '2021-01', 'tricolor', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('39', '1000000039', 'Hester', '', '2', '2021-12', 'brown', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('40', '1000000040', 'Cord', '2', '2020-12', 'black', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('41', '1000000041', 'Leila', 'chihuahua', '1', '2021-04', 'beige', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('42', '1000000042', 'Doris', '1', '2022-11', 'white', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('43', '1000000043', 'Erin', '2', '2021-03', 'blue', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('44', '1000000044', 'Nice', '1', '2018-07', 'tricolor', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('45', '1000000045', 'Koda', '2', '2019-06', 'white', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('46', '1000000046', 'Nut', '1', '2020-01', 'brown', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('47', '1000000047', 'Billy', '2', '2021-11', 'black', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `breed`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('48', '1000000048', 'Zeno', 'schnauzer', '2', '2022-10', 'black', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('49', '1000000049', 'Aro', '1', '2021-12', 'beige', 'medium', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('50', '1000000050', 'Rocky', '2', '2021-03', 'black', 'large', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('51', '1000000051', 'Milk', '1', '2021-11', 'white', 'small', '2');
INSERT INTO `dog_adoption`.`dog` (`id`, `transponder`, `name`, `sex`, `birthdate`, `color`, `size`, `status`) VALUES ('52', '1000000052', 'Mex', '1', '2018-09', 'brown', 'medium', '2');


-- update dog birthdate
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-01-00' WHERE (`id` = '1');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-04-00' WHERE (`id` = '2');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-04-01' WHERE (`id` = '3');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-01-01' WHERE (`id` = '4');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-12-01' WHERE (`id` = '5');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-04-01' WHERE (`id` = '6');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-11-01' WHERE (`id` = '7');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-07-01' WHERE (`id` = '8');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-05-01' WHERE (`id` = '9');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-07-01' WHERE (`id` = '10');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-08-01' WHERE (`id` = '11');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-05-01' WHERE (`id` = '12');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-09-01' WHERE (`id` = '13');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-05-01' WHERE (`id` = '14');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-07-01' WHERE (`id` = '15');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-05-01' WHERE (`id` = '16');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-04-01' WHERE (`id` = '17');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-02-01' WHERE (`id` = '18');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-05-01' WHERE (`id` = '19');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-01-01' WHERE (`id` = '20');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-09-01' WHERE (`id` = '21');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2018-11-01' WHERE (`id` = '22');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-07-01' WHERE (`id` = '23');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-07-01' WHERE (`id` = '24');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-01-01' WHERE (`id` = '25');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-03-01' WHERE (`id` = '26');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-11-01' WHERE (`id` = '27');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-07-01' WHERE (`id` = '28');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-08-01' WHERE (`id` = '29');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-06-01' WHERE (`id` = '30');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-03-01' WHERE (`id` = '31');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-05-01' WHERE (`id` = '32');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-07-01', `color` = 'white' WHERE (`id` = '33');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-07-01', `color` = 'black' WHERE (`id` = '34');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-05-01', `color` = 'brown' WHERE (`id` = '35');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2020-06-01' WHERE (`id` = '36');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-04-01', `color` = 'beige' WHERE (`id` = '37');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2018-03-01' WHERE (`id` = '38');
UPDATE `dog_adoption`.`dog` SET `breed` = 'mix', `birthdate` = '2020-06-01' WHERE (`id` = '39');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-11-01' WHERE (`id` = '40');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-01-01' WHERE (`id` = '41');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-04-01' WHERE (`id` = '42');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2018-11-01' WHERE (`id` = '43');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-09-01' WHERE (`id` = '44');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2021-03-01' WHERE (`id` = '45');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-03-01' WHERE (`id` = '46');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2019-06-01' WHERE (`id` = '47');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2022-11-01' WHERE (`id` = '48');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2018-07-01' WHERE (`id` = '49');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2018-06-01' WHERE (`id` = '50');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-05-01' WHERE (`id` = '51');
UPDATE `dog_adoption`.`dog` SET `birthdate` = '2017-09-01' WHERE (`id` = '52');


-- insert owner 
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (1, 'Malinde', 'Extill', '16 Farwell Plaza', 'mextill0@jalbum.net', '+7 (573) 505-2009', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (2, 'Flory', 'Loughnan', '0800 Arapahoe Court', 'floughnan1@skype.com', '+420 (888) 364-6364', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (3, 'Che', 'Hendron', '27 Loftsgordon Parkway', 'chendron2@patch.com', '+86 (704) 133-2875', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (4, 'Letitia', 'Armitage', '93830 Marcy Drive', 'larmitage3@infoseek.co.jp', '+690 (823) 207-7592', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (5, 'Mallory', 'Turn', '69798 Lukken Circle', 'mturn4@aboutads.info', '+84 (718) 993-1779', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (6, 'Tony', 'Prandoni', '0331 Calypso Park', 'tprandoni5@tinypic.com', '+420 (262) 264-0878', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (7, 'Jacqui', 'Clougher', '989 Nova Crossing', 'jclougher6@vimeo.com', '+51 (394) 231-9749', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (8, 'Mella', 'Astle', '7247 Montana Point', 'mastle7@addtoany.com', '+86 (613) 668-3831', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (9, 'Jonathan', 'Arrighini', '45791 Little Fleur Drive', 'jarrighini8@livejournal.com', '+86 (940) 678-2232', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (10, 'Francois', 'Bentsen', '24036 Miller Hill', 'fbentsen9@gov.uk', '+371 (897) 710-7049', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (11, 'Eduard', 'Weben', '244 Crest Line Place', 'ewebena@indiegogo.com', '+7 (863) 233-4587', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (12, 'Edy', 'Cochern', '6478 Crownhardt Way', 'ecochernb@nationalgeographic.com', '+41 (661) 887-1789', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (13, 'Kit', 'Towson', '6305 Hooker Terrace', 'ktowsonc@psu.edu', '+1 (727) 454-5245', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (14, 'Erv', 'Ockenden', '7 Oneill Court', 'eockendend@rambler.ru', '+86 (615) 899-7871', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (15, 'Elysia', 'Tart', '0278 Ohio Park', 'etarte@ca.gov', '+62 (711) 614-8354', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (16, 'Xylina', 'Mournian', '08429 Cordelia Place', 'xmournianf@about.com', '+45 (841) 170-8478', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (17, 'Aleda', 'Yakutin', '9603 Fairview Alley', 'ayakuting@bbb.org', '+62 (331) 940-5609', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (18, 'Colette', 'Nutbeam', '15 Kennedy Junction', 'cnutbeamh@phoca.cz', '+62 (280) 758-1713', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (19, 'Pepito', 'Acton', '179 Morningstar Place', 'pactoni@slate.com', '+351 (990) 601-4170', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (20, 'Eryn', 'Finnes', '63783 Pepper Wood Road', 'efinnesj@twitter.com', '+55 (629) 769-9813', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (21, 'Tulley', 'Lucio', '5306 Orin Alley', 'tluciok@parallels.com', '+86 (892) 272-3325', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (22, 'Lucinda', 'Beavan', '20 Anhalt Park', 'lbeavanl@archive.org', '+86 (366) 710-5263', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (23, 'Timmi', 'Jakeway', '40 Little Fleur Court', 'tjakewaym@hibu.com', '+86 (753) 603-2107', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (24, 'Leontine', 'Walrond', '31911 Sutherland Point', 'lwalrondn@usnews.com', '+84 (504) 982-5453', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (25, 'Geneva', 'Hendren', '719 Bunting Drive', 'ghendreno@aol.com', '+33 (588) 340-0844', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (26, 'Isahella', 'Vasilyev', '8 Homewood Circle', 'ivasilyevp@hexun.com', '+353 (640) 482-3335', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (27, 'Derrek', 'Triplett', '76 Elmside Hill', 'dtriplettq@telegraph.co.uk', '+60 (684) 605-3238', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (28, 'Ruddy', 'Ballister', '1698 Nova Alley', 'rballisterr@theguardian.com', '+63 (853) 286-7287', 3);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (29, 'Lishe', 'Veivers', '4 Maywood Hill', 'lveiverss@narod.ru', '+33 (411) 780-7647', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (30, 'Doris', 'Herald ', '45 Main Hill', 'dorisherald@telegrph.co.uk', '+41 (234) 235-6565', 1);
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (31, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (32, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (33, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (34, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (35, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (36, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (37, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (38, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (39, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (40, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (41, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (42, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (43, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (44, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (45, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (46, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (47, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (48, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (49, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (50, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (51, ' ', ' ', ' ', ' ', ' ', ' ');
insert into `dog_adoption`.`owner` (id, first_name, last_name, address, email, phone, status) values (52, ' ', ' ', ' ', ' ', ' ', ' ');


--  insert basic_vaccination
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000001', '2', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000002', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000003', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000004', '1', '2', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000005', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000006', '2', '1', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000007', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000008', '1', '2', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000009', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000010', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000011', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000012', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000013', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000014', '2', '2', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000015', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000016', '1', '2', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000017', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000018', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000019', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000020', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000021', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000022', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000023', '1', '2', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000024', '1', '1', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000025', '2', '2', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000026', '1', '2', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000027', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000028', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000029', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000030', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000031', '2', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000032', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000033', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000034', '1', '1', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000035', '1', '2', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000036', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000037', '2', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000038', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000039', '1', '1', '2', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000040', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000041', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000042', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000043', '1', '2', '1', '2', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000044', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000045', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000046', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000047', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000048', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000049', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000050', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000051', '1', '1', '1', '1', '1');
INSERT INTO `dog_adoption`.`basic_vaccination` (`transponder`, `distemper`, `hepatitis(CVH)`, `leptospirosis`, `parvovirosis`, `rabies`) VALUES ('1000000052', '1', '1', '2', '1', '1');


